backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "contactInfo"
    label: "Contact Info"
    files:
      - file: "src/content/contact.md"
        label: "Contact Information"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact"}
          - {label: Phones, name: phones, widget: list}
          - {label: "Contact Email", name: contactEmail, widget: string}
          - {label: "Work Email", name: workEmail, widget: string}
          - {label: "Newsletter Link", name: newsletterLink, widget: string}
          - {label: Instagram, name: instagram, widget: string}
          - {label: Instagram, name: instagram, widget: string}
          - {label: Facebook, name: facebook, widget: string}
          - {label: LinkedIn, name: linkedin, widget: string}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/home.md"
        label: "Home page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Description", name: "description", widget: string}
          - {label: "SEO Title", name: "seoTitle", widget: string}
          - {label: "SEO Description", name: "seoDescription", widget: string}
          - {label: "SEO Image", name: "seoImage", widget: image}
          - {label: "Body", name: "body", widget: markdown}
          - label: "List of works"
            name: "works"
            widget: "list"
            fields:
              - {label: Work, name: work, widget: relation, collection: works, searchFields: [title, explanation], valueField: title }

      - file: "src/content/pages/about.md"
        label: "About page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "SEO Title", name: "seoTitle", widget: string}
          - {label: "SEO Description", name: "seoDescription", widget: string}
          - {label: "SEO Image", name: "seoImage", widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "List of workers"
            name: "workers"
            widget: "list"
            fields:
              - {label: Worker, name: worker, widget: relation, collection: workers, searchFields: [title], valueField: title }

  - label: Works
    name: works
    folder: src/content/works
    editor:
      preview: false
    url: "{{title}}"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "work" }
      - {label: "SEO Title", name: "seoTitle", widget: string}
      - {label: "SEO Description", name: "seoDescription", widget: string}
      - {label: "SEO Image", name: "seoImage", widget: image}
      - { label: Name, name: title, widget: string }
      - { label: Explanation, name: explanation, widget: markdown }
      - {label: "Featured image", name: "featuredImage", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image }
          - {label: "Row(starts at 1)", name: row, widget: number }
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - {label: Tag, name: tag, widget: relation, collection: tags, searchFields: [title], valueField: title }
  
  - label: "Tags"
    name: tags
    folder: src/content/tags
    create: true
    editor:
      preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "tag" }
      - {label: Tag, name: title, widget: string}

  - label: "Type of Works"
    name: typeOfWorks
    folder: src/content/typeOfWorks
    create: true
    editor:
      preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "typeOfWork" }
      - {label: Type of Work, name: title, widget: string}

  - label: "Workers"
    name: workers
    folder: src/content/workers
    create: true
    editor:
      preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "worker" }
      - {label: Name, name: title, widget: string}
      - {label: Position, name: position, widget: string}
      - {label: Specialty, name: specialty, widget: string}
      - {label: City, name: city, widget: string}
      - {label: Curriculum, name: body, widget: markdown}

  - label: "Metadata"
    name: metadata
    files:
      - file: "src/content/metadata.md"
        label: "Metadata Information"
        name: "metadata"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "metadata"}
          - {label: "Facebook AppId", name: fbAppId, widget: string}
          - {label: "Twitter user", name: twitterUser, widget: string}