backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/home.md"
        label: "Home page"
        name: "home-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: "Body", name: "body", widget: markdown}
          - label: "List of works"
            name: "works"
            widget: "list"
            fields:
              - {label: Work, name: work, widget: relation, collection: work, searchFields: [name], valueField: name }


      - file: "src/content/pages/about.md"
        label: "About page"
        name: "about-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "List of workers"
            name: "workers"
            widget: "list"
            fields:
              - {label: Worker, name: worker, widget: relation, collection: workers, searchFields: [name], valueField: name }

  - label: Works
    name: works
    folder: src/content/works
    slug: "{{name}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "work" }
      - { label: Name, name: name, widget: string }
      - { label: Explanation, name: explanation, widget: markdown }
      - {label: "Featured image", name: "featuredImage", widget: "image"}
      - { label: Tags, name: tags, widget: relation, collection: typeworks, searchFields: [typeOfWork], valueField: typeOfWork }
  
  - label: "Type of Works"
    name: typeOfWorks
    folder: src/content/typeOfWorks
    create: true
    editor:
      preview: false
    fields:
      - {label: Type of Work, name: typeOfWork, widget: string}

  - label: "Workers"
    name: workers
    folder: src/content/workers
    create: true
    editor:
      preview: false
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Position, name: position, widget: string}
      - {label: Specialty, name: specialty, widget: string}
      - {label: City, name: city, widget: string}