backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - label: Works
    name: works
    folder: src/content/works
    slug: "{{name}}"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "work" }
      - { label: Name, name: name, widget: string }
      - { label: Explanation, name: explanation, widget: markdown }
      - {label: "Featured image", name: "featuredImage", widget: "image"}
      - { label: Tags, name: tags, widget: relation, collection: typeworks, searchFields: [typeOfWork], valueField: typeOfWork }

  - label: "Type of Works"
    name: typeOfWorks
    folder: src/content/typeOfWorks
    create: true
    editor:
      preview: false
    fields:
      - {label: Type of Work, name: typeOfWork, widget: string}